### ISSUE TITLE
CSS post-processor that adds rem unit fallbacks

### ISSUE THREAD

**Issue by robwierzbowski** [h5bp/lazyweb-requests#109]
The idea is pretty simple. Writing Sass mixins to generate two rules, one with modern units, and one with fallback units for older browsers, is shoehorning Sass into fixing what could be an automatic process with a tool better suited to the task. hsla and rgba need fallbacks, but their fallback values require human input. Rem, on the other hand, is just a calculation and can be taken care of by robots.
#### Current CSS Way

``` css
.selector {
  font-size: 16px;
  font-size: 1rem;
}
```
#### Current Sass way

``` scss
.selector {
  @include rem-fallback(width, 6rem);
  // This pretend mixin takes two arguments, the css rule 
  // and the value. By using math and a separate `$base-font-size`
  // settings variable, it calculates the fallback and compiles to:
  //   .selector {
  //    width: 96px;
  //    width: 6rem;
  //  }
  // There are tons of mixins that do this.
}
```
#### Better way (Possibly preprocessor agnostic, acting only on the CSS, possibly tied to a preprocessor to import needed variables)

``` scss
html {
  font-size: 200%;
}
.selector {
  width: 5rem;
}
// On CSS compiling, Grunt/etc. runs rem fallback post-processor
html {
  font-size: 200%;
}
.selector {
  width: 160px;
  width: 6rem;
}
```
