### ISSUE TITLE
A Polyfill for `@media (hover)`

### ISSUE THREAD

**Issue by cvrebert** [h5bp/lazyweb-requests#159]
[From the CSS Media Queries Level 4 draft](http://dev.w3.org/csswg/mediaqueries4/#hover).

I think a server-side CSS postprocessor that converts
```css
@media (hover) {
  .some-selector {
    prop: value;
  }
}
```
into 
```css
.no-touch .some-selector {
  prop: value;
}
```
(with the name of the `.no-touch` class being customizable) would be a good option.
