### ISSUE TITLE
Sass shouldn't suck at media queries

### ISSUE THREAD

**Issue by valpackett** [h5bp/lazyweb-requests#72]
If I want to make a responsive design with modular stylesheets right now, I have to do something like this:

``` css
/* main.scss */
$mq-medium: "screen and (min-width: 720px)";
@import "buttons";
@import "panes";

/* buttons.scss */
.btn {
  display: inline;
  @media #{$mq-medium} {
    display: block;
  }
}

/* panes.scss */
.pane {
  width: 100%;
  @media #{$mq-medium} {
    width: 50%;
    float: left;
  }
}
```

But _even that doesn't work_!  Because @-rules are so damn special you can't interpolate there.

It should be something like this:

``` css
$mq-medium: "screen and (min-width: 720px)";
@import "buttons";
@import "panes";
@media $mq-medium;

/* buttons.scss */
.btn {
  display: inline;
  @extend-media $mq-medium {
    display: block;
  }
}

/* panes.scss */
.pane {
  width: 100%;
  @extend-media $mq-medium {
    width: 50%;
    float: left;
  }
}
```

And be optimized on compilation, like extend. So the compiled output should be:

``` css
.btn {
  display: inline;
}
.pane {
  width: 100%;
}
@media screen and (min-width: 720px) {
  .btn {
    display: block;
  }
  .pane {
    width: 50%;
    float: left;
  }
}
```
